-- 코드를 입력하세요
SELECT ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS
    USING (ANIMAL_ID)
WHERE ANIMAL_INS.SEX_UPON_INTAKE REGEXP 'Intact' AND
    ANIMAL_OUTS.SEX_UPON_OUTCOME REGEXP 'Spayed|Neutered'
ORDER BY ANIMAL_ID ASC;