-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_PRICE
FROM FOOD_ORDER 
INNER JOIN FOOD_PRODUCT
    USING (PRODUCT_ID)
WHERE MONTH(PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_PRICE DESC, PRODUCT_ID
;

